import assert from 'node:assert/strict';
import {DOMParser} from '../native/node_modules/@xmldom/xmldom/lib/index.js';
import {validateData,prepare,stats,deriveVisits} from '../dist/core.js';
import {parseImport,mergeData} from '../dist/import.js';
const empty=()=>({points:[],places:[],visits:[]});
const v=(arrival,departure,latitude=30)=>({latitude,longitude:-97,arrival,departure});
const data=validateData({visits:[v(0,3600000),v(0,3600000)]});
assert.equal(stats(prepare(data)).hours,1);
assert.equal(stats(prepare(mergeData(data,data))).hours,1);
assert.equal(mergeData(data,validateData({visits:[v(3600000,7200000)]})).visits.length,2);
assert.throws(()=>mergeData(data,validateData({visits:[v(0,3600000,31)]})),/overlap/);
const xml='<gpx xmlns="http://www.topografix.com/GPX/1/1"><trk><trkseg><trkpt lat="30" lon="-97"><time>2026-09-01T10:00:00Z</time></trkpt><trkpt lat="30" lon="-97"><time>2026-09-01T10:05:00Z</time></trkpt><trkpt lat="30" lon="-97" /></trkseg><trkseg><trkpt lat="30" lon="-97"><time>2026-09-01T10:10:00Z</time></trkpt></trkseg></trk></gpx>';
const parsed=parseImport(xml,DOMParser);assert.equal(parsed.skipped,1);assert.equal(parsed.data.points.length,3);assert.equal(deriveVisits(parsed.data.points)[0].durationMinutes,5);
assert.equal(mergeData(parsed.data,parsed.data).points.length,3);
assert.equal(parseImport(xml.replaceAll('gpx','g:gpx').replace('xmlns=','xmlns:g='),DOMParser).data.points.length,3);
assert.throws(()=>parseImport('<!DOCTYPE gpx><gpx/>',DOMParser),/document type/);
assert.throws(()=>parseImport('<gpx><trkpt',DOMParser),/valid/);
assert.throws(()=>parseImport('<gpx><wpt lat="30" lon="-97"/></gpx>',DOMParser),/timestamped/);
assert.throws(()=>parseImport('{"points":[{"latitude":999}]}',DOMParser),/valid/);
const sparse=validateData({points:[{latitude:30,longitude:-97,timestamp:0},{latitude:30,longitude:-97,timestamp:3600000}]});assert.equal(deriveVisits(sparse.points).length,0);assert.equal(stats(prepare(sparse)).distance,0);
assert.deepEqual(mergeData(empty(),empty()),empty());
console.log('PASS: duplicate and repeat import, merge preservation, overlapping visit rejection, GPX timestamps/namespaces/segments, malformed XML and entity rejection, sparse-history honesty.');
