import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import ts from '../native/node_modules/typescript/lib/typescript.js';import {validateData} from '../dist/core.js';
const sql=new DatabaseSync(':memory:');let injectedFailure=false;
const db={execAsync:async q=>sql.exec(q),getFirstAsync:async(q,...v)=>sql.prepare(q).get(...v),getAllAsync:async(q,...v)=>sql.prepare(q).all(...v),runAsync:async(q,...v)=>{if(injectedFailure&&q.startsWith('INSERT OR IGNORE INTO points'))throw Error('disk full');return sql.prepare(q).run(...v);},withExclusiveTransactionAsync:async fn=>{sql.exec('BEGIN');try{await fn(db);sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');throw e;}}};
let legacy=JSON.stringify({realPoints:[{latitude:30,longitude:-97,timestamp:1}],demoMode:false,onboardingComplete:true});
const modules={'expo-sqlite':{openDatabaseAsync:async()=>db},'@react-native-async-storage/async-storage':{default:{getItem:async()=>legacy,removeItem:async()=>{legacy=null;}}},'../shared/core':{validateData}};
function load(path,mods){const exports={};const code=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports,require:name=>{assert(name in mods,name);return mods[name];}});return exports;}
const storage=load(new URL('../native/src/services/storage.ts',import.meta.url),modules);
await storage.migrateLegacy();assert.equal((await storage.readData()).points.length,1);await storage.migrateLegacy();assert.equal((await storage.readData()).points.length,1);
await storage.appendPoints([{latitude:30,longitude:-97,timestamp:2}],true);assert.equal((await storage.readData()).points.length,1);
await storage.setMeta('tracking','true');await storage.setMeta('session','test');await storage.appendPoints([{latitude:30,longitude:-97,timestamp:2}],true);await storage.appendPoints([{latitude:30,longitude:-97,timestamp:2}],true);assert.equal((await storage.readData()).points.length,2);
injectedFailure=true;await assert.rejects(storage.replaceData({points:[{latitude:31,longitude:-97,timestamp:3}],visits:[],places:[]}));injectedFailure=false;assert.equal((await storage.readData()).points.length,2);
let handler,started=false,auth='granted';const location={getBackgroundPermissionsAsync:async()=>({status:auth}),hasStartedLocationUpdatesAsync:async()=>started,stopLocationUpdatesAsync:async()=>{started=false;},requestForegroundPermissionsAsync:async()=>({status:auth}),requestBackgroundPermissionsAsync:async()=>({status:auth}),startLocationUpdatesAsync:async()=>{started=true;},Accuracy:{Balanced:3},ActivityType:{Other:1}};
const tracking=load(new URL('../native/src/services/tracking.ts',import.meta.url),{'expo-location':location,'expo-task-manager':{defineTask:(_,fn)=>handler=fn,isAvailableAsync:async()=>true},'./storage':storage});
await tracking.startBackground();assert.equal(await tracking.trackingStatus(),true);await handler({data:{locations:[{timestamp:4,coords:{latitude:30,longitude:-97,accuracy:10}}]}});assert.equal((await storage.readData()).points.length,3);
await tracking.stopBackground();await handler({data:{locations:[{timestamp:5,coords:{latitude:30,longitude:-97,accuracy:10}}]}});assert.equal((await storage.readData()).points.length,3);
auth='denied';await assert.rejects(tracking.startBackground());assert.equal(await tracking.trackingStatus(),false);
await storage.replaceData({points:[],visits:[],places:[]});await storage.discardLegacy();assert.equal((await storage.readData()).points.length,0);assert.equal(legacy,null);
console.log('PASS: SQLite legacy migration/idempotence, duplicate points, transactional rollback, permission denial, background task saving, pause ignores queued samples, history deletion. Location APIs mocked; device delivery not tested.');
