import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';import * as core from '../dist/core.js';import * as imports from '../dist/import.js';
const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8'),source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace(/^import .*?;\n/gm,'');const storage={};
function boot(){const els={};class El{constructor(){this.style={setProperty(){}};this.dataset={};this.value='';this.events={};}set innerHTML(v){this._html=v;for(const m of v.matchAll(/id="([^"]+)"/g))if(!els[m[1]])els[m[1]]=new El()}get innerHTML(){return this._html}setAttribute(k,v){this[k]=v}removeAttribute(k){delete this[k]}querySelectorAll(){return []}addEventListener(k,f){this.events[k]=f}showModal(){this.open=true}close(){this.open=false}reset(){}append(){}click(){}remove(){}}
for(const m of html.matchAll(/id="([^"]+)"/g))els[m[1]]=new El();const doc={getElementById:id=>els[id]||null,querySelectorAll:()=>[],querySelector:()=>new El(),addEventListener(){},createElement:()=>new El(),body:new El()};const ctx=vm.createContext({...core,...imports,document:doc,window:{scrollTo(){},addEventListener(){}},navigator:{},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v,removeItem:k=>delete storage[k]},setTimeout(){return 1},clearTimeout(){},requestAnimationFrame:f=>f(),Date,Math,Number,JSON,Array,Object,Blob,URL,File});vm.runInContext(source,ctx);return {els,run:code=>vm.runInContext(code,ctx)}}
let b=boot();assert.equal(b.els.heroPlaces.textContent,8);b.els.demoToggle.onclick();assert.equal(b.els.heroPlaces.textContent,0);Object.assign(b.els.visitName,{value:'Library'});b.els.visitCategory.value='School';b.els.visitLat.value='30';b.els.visitLon.value='-97';b.els.arrival.value='2026-09-01T10:00';b.els.departure.value='2026-09-01T12:00';b.els.visitForm.onsubmit({preventDefault(){}});assert.equal(b.els.heroPlaces.textContent,1);assert.match(b.els.heroDetail.textContent,/2 hours/);b=boot();assert.equal(b.els.heroPlaces.textContent,1);b.els.demoToggle.onclick();assert.equal(b.els.heroPlaces.textContent,8);b.els.demoToggle.onclick();assert.equal(b.els.heroPlaces.textContent,1);b.els.openStory.onclick();assert.equal(b.els.storyCount.textContent,'1 / 10');for(let i=0;i<9;i++)b.els.storyNext.onclick();assert.equal(b.els.storyCount.textContent,'10 / 10');assert(b.els.makeShare);b.els.storyClose.onclick();b.els.openStory.onclick();assert.equal(b.els.storyCount.textContent,'1 / 10');b.els.deleteBtn.onclick();assert.equal(b.els.confirmDialog.open,true);assert.equal(b.els.heroPlaces.textContent,1);b.els.confirmAction.onclick();assert.equal(b.els.heroPlaces.textContent,0);console.log('PASS: app initialization, manual visit save/reload, demo isolation, story navigation/reset, deletion confirmation. DOM simulation only; physical iPhone not tested.');

b.run(`const drawn=[];const canvasMock={font:'',measureText(t){return {width:String(t).length*Number(this.font.match(/(\\d+)px/)[1])*.65};},fillText(t,x,y){drawn.push({text:t,width:this.measureText(t).width});}};drawFittedText(canvasMock,'An exceptionally long place name '.repeat(4),0,0,920,55);drawFittedText(canvasMock,'123,456,789,123',0,0,384,70);if(drawn.some(d=>d.width> (d===drawn[0]?920:384)))throw Error('Share text exceeds card');`);
assert.equal(b.els.storyNext['aria-label'],'Next story');
console.log('PASS: share-card text stays within measured bounds; recap controls have correct labels. This is not a screenshot check.');
